# Generated by Django 5.2.8 on 2025-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_chatsession_text_mode_alter_chatmessage_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="text_mode",
            field=models.CharField(
                choices=[("formal", "FORMAL"), ("informal", "INFORMAL")],
                max_length=20,
                null=True,
            ),
        ),
    ]
