# Generated by Django 5.2.8 on 2025-12-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_chatsession_text_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
